AllCops:
  NewCops: disable

Style/FrozenStringLiteralComment:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/SymbolArray:
  Enabled: true
  EnforcedStyle: brackets

Metrics/MethodLength:
  Max: 20

Style/NumericPredicate:
  Enabled: false

Style/GuardClause:
  Enabled: false

Naming/PredicateName:
  Enabled: false

Naming/MemoizedInstanceVariableName:
  Enabled: false

Style/VariableInterpolation:
  Enabled: false
